# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=8)),
            ],
        ),
    ]
